# Generated by Django 5.1.7 on 2025-03-31 11:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=10)),
                ('installation_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric1', models.FloatField()),
                ('metric2', models.FloatField()),
                ('metric3', models.FloatField()),
                ('metric4', models.FloatField()),
                ('metric5', models.FloatField()),
                ('metric6', models.FloatField()),
                ('metric7', models.FloatField()),
                ('metric8', models.FloatField()),
                ('metric9', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='maintenance_app.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('scheduled', 'Scheduled Maintenance'), ('predictive', 'Predictive Maintenance'), ('failure', 'Failure Event')], max_length=50)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('downtime_hours', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='maintenance_app.device')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('failure_predicted', models.BooleanField()),
                ('failure_probability', models.FloatField()),
                ('recommended_action', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='maintenance_app.device')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
