# Generated by Django 5.1.7 on 2025-03-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0002_modeltraininglog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltraininglog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Model Training Log', 'verbose_name_plural': 'Model Training Logs'},
        ),
        migrations.RenameField(
            model_name='modeltraininglog',
            old_name='metrics',
            new_name='performance_metrics',
        ),
        migrations.RenameField(
            model_name='modeltraininglog',
            old_name='training_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='modeltraininglog',
            old_name='data_file',
            new_name='training_file',
        ),
        migrations.RemoveField(
            model_name='modeltraininglog',
            name='success',
        ),
    ]
