# Generated by Django 5.1.7 on 2025-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0003_alter_modeltraininglog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltraininglog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='modeltraininglog',
            old_name='training_file',
            new_name='data_file',
        ),
        migrations.RemoveField(
            model_name='modeltraininglog',
            name='performance_metrics',
        ),
        migrations.AddField(
            model_name='modeltraininglog',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='modeltraininglog',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
