# Generated by Django 5.1.7 on 2025-03-31 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0004_alter_modeltraininglog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('model_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='modeltraininglog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Training Log', 'verbose_name_plural': 'Training Logs'},
        ),
        migrations.AlterField(
            model_name='modeltraininglog',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modeltraininglog',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance_app.modelversion'),
        ),
    ]
